### ISSUE TITLE
Support iPad (not just iPhone)

### ISSUE THREAD

**Issue by adamcogan** [SSWConsulting/SSW.Rewards.Mobile#448]
1. Support iPad (not just iPhone) 

2. Explain the changes you had to make

**Comment by matt-goldman** [comment]
Hi @adamcogan 

> Support iPad (not just iPhone)

Done:
<img width="600" src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/19944129/8281c495-8c51-49c3-80c1-81859a8076cb"/>
**Figure: Latest iOS build running (from the App Store) on iPad**

<br><br>
> Explain the changes you had to make

In a previous build, we intentionally removed iPad support (in this commit: https://github.com/SSWConsulting/SSW.Rewards.Mobile/commit/844852aad8686ebd973a535dc5eee7e55bf16234). This was because there was an issue with the screenshots on the App Store and the version in production at the time had a bug. iPad usage for this app is minimal (see figure below), so we prioritised releasing a build with the fix ASAP over ensuring iPad was targetted.

<img width="1450" alt="image" src="https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/19944129/dcfe5edd-bc99-4d9a-8a33-c7dc671affe1">

**Figure: iPad usage (4 installs, one of which is me), is 2.23% of total installs (179) on iOS (1.68% excluding me)**

The change involves specifying the `UIDeviceFamily` key in the `info.plist` file. Previously we had:

```xml
<key>UIDeviceFamily</key>
    <array>
        <integer>1</integer>
	<integer>2</integer>
    </array>
</key>
```

1 represents iPhone, 2 represents iPad, 0 represents all. In the above mentioned commit, we removed 2. However, 0 is the default, so to fix it, rather than add that back, or set it to 0, we simply removed the `UIDeviceFamily` key altogether. This enabled the lates build to target iPad as well as iPhone devices (and macOS too, as by default all iOS apps are now available via the Mac App Store as well).

**Comment by adamcogan** [comment]
I understand at only 2% usage it is not worth it.

Curious, how much effort to fully support an ipad? 
-a

**Comment by matt-goldman** [comment]
> Curious, how much effort to fully support an ipad?

Implementation is relatively straightforward. We can adapt the layout/design for iPad (or any tablet). But we need the visual designs for that. So bulk of the effort is for the designers.

I think there are a few areas where we would like to refresh the UI, so if you're keen to allocate that to the designers, this could be one of the tasks on their list.
