### ISSUE TITLE
🐛 iOS | Leaderboard displays incorrect information

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#457]
**Steps to reproduce:**
1. Open the Leaderboard page. The This Month list is displayed.
2. Switch to either This Year or All Time list
3. Switch back to This Month list

**Expected result:**
The This Month list from step 1 is displayed

**Actual result:**
Some information from the list selected on step 2 is still displayed. It's gone if you scroll down and back.
On the video below points for Camilla are incorrect.

https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/45f8fdcb-3dc4-4549-ae0c-d3313c58aeb1

**Comment by matt-goldman** [comment]
Hi @AntPolkanov, this issue appears to have been resolved in the most recent build. Can you please confirm?

Can you confirm when you observed this? I think it's either something that was fixed in [this commit](https://github.com/SSWConsulting/SSW.Rewards.Mobile/commit/d3f351e868b34079bd999375e42797b5aacbbf75), or if not could be a fix in .NET 8 (https://github.com/dotnet/maui/pull/15831).

**Comment by matt-goldman** [comment]
Confirmed as resolved by me, @AntPolkanov, @sethdailyssw and @ricksu978
