### ISSUE TITLE
🐛 SSW People | Profile photos have different sizes

### ISSUE THREAD

**Issue by camillars** [SSWConsulting/SSW.Rewards.Mobile#646]
Cc: @AntPolkanov @tkapa @matt-goldman @zacharykeeping 

Hi 

### Describe the Bug
In the past, we added criteria to make the photos size consistent and some are still too big or too small when you swipe 'SSW People'.

### To Reproduce
1. Go to 'SSW People'
2. Swipe to see different profiles
3. See error

### Expected Behavior

I expected the photos to have similar height in size.

### Tasks
- [ ] Investigate
- [ ] Fix

### Acceptance Criteria

- [ ] Meets Definition of Done - {{ LINK }}
- [ ] ...

### Environment
 - Device: iPhone 15 Pro Max
 - OS: 17.3

### Screenshots
![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/53064613/aafd729a-3ec3-43d8-a284-d19723602faf)

![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/53064613/bea9be60-bbf4-4af4-989d-ace7c633162f)

![image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/53064613/ab477110-deac-46ec-8f0e-c76306fea07b)

Thanks!

**Comment by camillars** [comment]
@SSWConsulting/sswdesigners 

Betty, Geordie, Tiago - can any of you look into this issue, please?

**Comment by Geordie88** [comment]
Hi Tylah,

As per our conversation it is simpler for me to hand over the files and profiles needing updating to you rather than organising permissions for my to edit the rewards profiles 😊


  1.  Please add these images to the relevant profiles [​Folder icon]  Fixed-Profile-Images<https://sswcom.sharepoint.com/:f:/r/sites/SSWDESIGN/Shared%20Documents/General/Project-SSWRewards/Assets/Fixed-Profile-Images?csf=1&web=1&e=suy0xn>

Hi Camilla,

We are lacking good ¾ length body shots of the following people:

High priority (worst pics)
               Alex Rothwell
               Andrew Harris
               Hugo Pernet

Low priority
               Gert marx
               Jack Pettit
               Jospeh Fernandez
               Kiki Biacatti












Geordie Robinson   |   SSW Associate UI/UX Designer<http://www.ssw.com.au/People/Geordie-Robinson?utm_source=emailsignature>   |    +61 477 755 584<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Ping me on ***@***.***>

**Comment by Geordie88** [comment]
Hey Geordie,

Done – You should be able to see the new images appearing in the app now. This week I’m going to be working on some improvements to the Admin portal so that we can let people add images themselves.






Tylah Kapa   |   SSW Software Engineer<http://www.ssw.com.au/People/Tylah-Kapa?utm_source=emailsignature>   |    +61 451 380 844<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Ping me on ***@***.***>



From: Geordie Robinson [SSW] ***@***.***>
Date: Friday, 9 February 2024 at 17:37
To: Tylah Kapa [SSW] ***@***.***>
Cc: Team mention ***@***.***>, SSWConsulting/SSW.Rewards.Mobile ***@***.***>, SSWConsulting/SSW.Rewards.Mobile ***@***.***>
Subject: RE: [SSWConsulting/SSW.Rewards.Mobile] 🐛 Profile photos have different sizes (Issue #646)
Hi Tylah,

As per our conversation it is simpler for me to hand over the files and profiles needing updating to you rather than organising permissions for my to edit the rewards profiles 😊


  1.  Please add these images to the relevant profiles [​Folder icon]  Fixed-Profile-Images<https://sswcom.sharepoint.com/:f:/r/sites/SSWDESIGN/Shared%20Documents/General/Project-SSWRewards/Assets/Fixed-Profile-Images?csf=1&web=1&e=suy0xn>

Hi Camilla,

We are lacking good ¾ length body shots of the following people:

High priority (worst pics)
               Alex Rothwell
               Andrew Harris
               Hugo Pernet

Low priority
               Gert marx
               Jack Pettit
               Jospeh Fernandez
               Kiki Biacatti












Geordie Robinson   |   SSW Associate UI/UX Designer<http://www.ssw.com.au/People/Geordie-Robinson?utm_source=emailsignature>   |    +61 477 755 584<https://www.ssw.com.au/ssw/Company/Offices/?utm_source=emailsignature>   |   Ping me on ***@***.***>

**Comment by AntPolkanov** [comment]
v2024 doesn't have photos of SSW employees.
Closing this ticket.
