### ISSUE TITLE
🐛 Data - Initialise should not remove existing profiles

### ISSUE THREAD

**Issue by tkapa** [SSWConsulting/SSW.Rewards.Mobile#714]
Hey @matt-goldman,

- [ ] {{ TODO: Flesh this out and mark as ready }}

**Comment by tkapa** [comment]
Hey @matt-goldman,

1. Please flesh this one out when you can.

**Comment by matt-goldman** [comment]
Hey @tkapa 

I think @AndreasLengkeek was concerned that we have some initialisation logic that overwrites profiles with new data rather than adding new data.

I think we can probably remove it altogether though. The sample data isn't really sample data at all - it's specific actual production data used for SSW. I think we can remove the current data initialisation logic, and instead create a bulk importer. Then we could create sample/dummy/seed data in json that can be imported for local dev or for demoing or testing out the solution.

Can we discuss this with the team? Or should we create a GitHub discussion for this?

**Comment by tkapa** [comment]
Hey @matt-goldman,

I'll set up a meeting for this one when everyone's schedules are aligned.

**Comment by matt-goldman** [comment]
(checked by @AntPolkanov and @zacharykeeping)
Hi @tkapa 

I've been working through this with Anton and Zach. I think this issue relates to this line of code: https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/a3e157b976932a3e7a9c8b031a5ab36fc36fe6fb/src/Application/System/Commands/Common/SampleDataSeeder.cs#L143

```csharp
//remove removed profiles
        var profileNames = profiles.Select(p => p.Name).ToArray();
        var profilesToRemove = await _context
            .StaffMembers
            .Where(sm => !profileNames.Contains(sm.Name))
            .ToArrayAsync(cancellationToken);
        _context.StaffMembers.RemoveRange(profilesToRemove);
        await _context.SaveChangesAsync(cancellationToken);
```

This is removing any staff members from the database that are not present in the Excel file. I believe the concept here was originally to use the Excel file as the "source of truth" for profiles.

However, we now have the admin portal and don't use this approach anymore. Also, this entire process will be superseded by #540.

As such, I believe this is redundant and can now be closed.
