### ISSUE TITLE
🐛 Admin | Draw prize not working

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#921]
Cc: @camillars

As per our conversation, the draw prize function not working.

### Screenshots

![Image](https://github.com/SSWConsulting/SSW.Rewards.Mobile/assets/123032112/c828f1f1-f8b2-4c87-b2e9-bf1567bd383a)

**Figure: unhandled exception**

Thanks!

**Comment by camillars** [comment]
@AntPolkanov 
cc @zacharykeeping 

this gives me the impression the bug was fixed - was it? 
or the functionality was hidden?

if it was hidden, do we still have an open issue to get this sorted?

thanks

**Comment by zacharykeeping** [comment]
> [@AntPolkanov](https://github.com/AntPolkanov) cc [@zacharykeeping](https://github.com/zacharykeeping)
> 
> this gives me the impression the bug was fixed - was it? or the functionality was hidden?
> 
> if it was hidden, do we still have an open issue to get this sorted?
> 
> thanks

Hey Camilla,

We're just hiding the button from now as we discovered that this functionality was never completed and such should have never been shown in the UI, and implementing it now would lead to issues as it would mean assigning a prize to someone would reduce their points balance due to how the balance is calculated.

For the time being we'll just need to handle handing out the prizes manually. There's a new PBI at #938 to investigate and implement a solution to this.

Thanks

**Comment by zacharykeeping** [comment]
As per my conversation with @camillars this should be re-enabled and updated to show a simple popup with a dropdown to selected 1-point prizes to assign to users.

Reopening to add this functionality.
