### ISSUE TITLE
✨ Mobile | Camera on the latest iPhone doesn't focus and freezes on the next attempt to open

### ISSUE THREAD

**Issue by AntPolkanov** [SSWConsulting/SSW.Rewards.Mobile#948]
Cc: @camillars

### Tasks

- [ ] ...
- [ ] ...

### Acceptance Criteria

- [ ] Meets Definition of Done - https://github.com/SSWConsulting/SSW.Rewards.Mobile/blob/main/_docs/Definition-of-Done.md
- [ ] ...

### Screenshots

Thanks!

**Comment by camillars** [comment]
Hi @AntPolkanov 

adding context:

at the last few Tina conferences, Levi and I couldn't use the QR code scanner functionality - it would not focus on the image properly to be able to scan the code.

I am on an iPhone 15 pro max - Levi uses an iPhone 15 Pro afaik.

Thanks.

**Comment by bradystroud** [comment]
FYI this is not unique to SSW Rewards - it happens everywhere there is a built-in code scanner in an app. It effects all iPhone 15s - the new main camera cannot focus on things up close. 

https://discussions.apple.com/thread/255148370?sortBy=best
There are a bunch of discussions like above where other people have the same problem.

**Comment by zacharykeeping** [comment]
The focus issue on newer iPhones should be improved after #953 which will improve the zoom depending on the device used.

That said, due to the increased minimum focus distance on newer iPhones, these devices will still need to maintain more of a distance from the QR code in order to focus - if it's not in focus, keep moving back. The increased zoom should allow it to be scanned once it's moved back enough to focus.

A better solution would be allow adjusting lenses but the current code scanning library doesn't allow this. We'll need to research something better.

**Comment by zacharykeeping** [comment]
Done - this should be much improved now.

We've moved to a new scanning library which works better out of the box, and allows us better control over things like zooming which can switch between lenses.

<img width="400" src="https://github.com/user-attachments/assets/409c8cc6-0064-48d1-91c4-17193b373fba" />

**Figure: New zoom buttons**
